### ISSUE TITLE
is there an Lwt_log.file equivalent in Logs ?

### ISSUE THREAD

**Issue by cedlemo** [dbuenzli/logs#20]
Based on this issue https://github.com/ocsigen/lwt/issues/468, it seems that `Logs` should be preferred over `Lwt_log`, however after reading the docs, it seems for me (maybe I was not able to understand the doc sorry) that Logs is only for console output and that I can not use it for logging in a file like with [Lwt_log.file](https://ocsigen.org/lwt/2.7.1/api/Lwt_log#VALfile).

Could you confirm this ?

**Comment by dbuenzli** [comment]
> it seems for me (maybe I was not able to understand the doc sorry) that Logs is only for console output and that I can not use it for logging in a file like with Lwt_log.file.

No. You simply need to write and [setup](http://erratique.ch/software/logs/doc/Logs.html#setupreporter) your own [reporter](http://erratique.ch/software/logs/doc/Logs.html#reporters). It shouldn't be too hard to tweak [this example](http://erratique.ch/software/logs/doc/Logs_lwt.html#report_ex) to make it log to a file.

Btw. I prefer if these questions occur on http://discuss.ocaml.org rather than on the issue tracker.

**Comment by cedlemo** [comment]
> Btw. I prefer if these questions occur on http://discuss.ocaml.org rather than on the issue tracker.

Ok, Thanks.
